# -*- coding: utf-8 -*-

SOCKS_VERSION_V = 5

SOCKS_NO_ACCEPT_METHOD = 0xff
SOCKS_AUTH_NONE = 0x00

SOCKS_ATYP_IPV4 = 1
SOCKS_ATYP_IPV6 = 4
SOCKS_ATYP_DOMAIN = 3

SOCKS_CMD_CONNECT = 1
SOCKS_CMD_BIND = 2
SOCKS_CMD_UDP = 3

SOCKS_REP_CON_SUC = 0x00
SOCKS_REP_NET_ERO = 0x03
SOCKS_REP_CON_RFS = 0x05
SOCKS_REP_CMD_UNK = 0x07